version: "3.8"

services:
  backend:
    image: jl115/lb-chat:latest
    container_name: chat-backend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
      - ki
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: lb-chat
      DB_PORT: 5432
      KI_HOST: ki
      KI_PORT: 11434

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lb-chat
    ports:
      - "5432:5432"

  ki:
    image: jl115/tinyllm:latest
    container_name: chat-ki
    ports:
      - "11434:11434"
